name: Set Branch Protection

on:
  push:
    branches:
      - main

jobs:
  set-branch-protection:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set branch protection
      uses: actions/github-script@v5
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const branch = 'main';
          const owner = context.repo.owner;
          const repo = context.repo.repo;

          await github.rest.repos.updateBranchProtection({
            owner,
            repo,
            branch,
            required_status_checks: {
              strict: true,
              contexts: ["Continuous Integration", "Merge Pull Request", "Update Branch"]
            },
            enforce_admins: true,
            required_pull_request_reviews: {
              dismiss_stale_reviews: true,
              require_code_owner_reviews: true,
              required_approving_review_count: 1
            },
            restrictions: null
          });
