name: Update Branch

on:
  issue_comment:
    types: [created]

jobs:
  update-branch:
    if: >
      github.event.issue.pull_request &&
      github.event.comment.body == '/update-branch' &&
      github.event.comment.user.id == github.event.issue.user.id
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update Branch
        uses: actions/github-script@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          script: |
              const { owner, repo, number: pull_number } = context.issue;

              await github.pulls.updateBranch({ owner, repo, pull_number });
